### PR TITLE
Added declare strict types rule

### PR DESCRIPTION
**Pull request by Robinamixan**
# PHP-CS: Declare strict types rule

## Introduction
Update cs fixer rule for forcing add declare(strict_types=1) to all files.

## Proposal
In all PHP >= 7.0 files we should use delare strict type for decreasing errors in application.
```php
<?php

declare(strict_types=1);
```

## Benefits
Decrease type errors in applications.

### CODE REVIEW

**Review by ashestak — DISMISSED** [review]

**Review by kimu — DISMISSED** [review]

**Review by vilewish — DISMISSED** [review]

**Review by mikitafreeman — CHANGES_REQUESTED** [review]
I agree with this, but could you provide information on the implementation of this. We cannot just add this rule for cs fixer. If we add  `declare_strict_types=true` for all files, we cannot be sure that we have no type errors in the code, since we do not have 100%  test coverage. So we can only add this for new files.

**Comment by Robinamixan** [comment]
@NikDevPHP We can't set rule only for new/changed files. I understand that we can't apply this rule everywhere immediately(as on inventory_be). But at least we should add `declare_strict_types=true` to all new files and to updated files. After some time we will be able enable rule.

**Comment by AliakseiBurak** [comment]
I think there should be more investigations on this should be made. In fact, we have services with good test coverage and already implemented declare strict type in most files (indexer instances, payment, checkout, etc.). This rule can be enabled for them.
Also should mention that automation tests can find problems I think. Can we rely on this?
So far would be better to have a list where we can implement this rule straight away and where this one is blocked by low test coverage problem.
But in general I agree.

**Review by AliakseiBurak — DISMISSED** [review]

**Review by TomCawthorn — DISMISSED** [review]

**Review by AlekseyKrupsky — DISMISSED** [review]

**Review by rabie-sulman — DISMISSED** [review]

**Comment by rabie-sulman** [comment]
This PR was approved by the majority - approvals gone as we rebased after another PR merged and created conflicts. I will force merge

**Pull request merged**
